backend/dataprocessing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/posts/urls.py
from django.urls import path
from . import views
from . import api

app_name = "posts"

urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    path("posts/", views.postsView, name="posts"),
    path("tell-me/", views.WriteYourOwn.as_view(), name="tell-me"),
    path("parse/", views.ProcessData.as_view(), name="parse"),
    path("chatbot/", views.Chatbot.as_view(), name="chatbot"),
    path("api/posts/all", api.getPosts, name="api-all-posts"), 
    path("api/posts/<int:id>", api.detailPost, name="api-detail-post"),
    path("api/posts/create", api.createPost, name="api-create-post"),
    path("api/posts/search", api.searchPost, name="api-search-post"),
    path("api/posts/parse", api.parsePost, name="api-parse-post"),
    path("api/comments/create", api.createComment, name="api-create-comment"),
    path("api/comments/<int:post_id>", api.getComments, name="api-comments-post-id"),
    path("api/chatbot", api.chatBot, name="api-chatbot"),
]

backend/posts/models.py
from django.db import models
from django.core.serializers.json import DjangoJSONEncoder
from .data_processing import tokenize_words, stem_sentence, pos_tags_sentence, lemmatize_sentence, remove_stop_words


class Post(models.Model):
    title = models.CharField(max_length=300, null=False, unique=True)
    username = models.CharField(max_length=50, null=False)
    ups = models.IntegerField(default=0, blank=True)
    downs = models.IntegerField(default=0, blank=True)
    subreddit = models.CharField(max_length=20, null=False, default="")
    created = models.DateTimeField(auto_now_add=True)
    url = models.URLField(verbose_name="post_url", null=False)

    class Meta:
        order_with_respect_to = "created"

    def save(self, *args, **kwargs):
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.title} by {self.username}"


class Comment(models.Model):
    username = models.CharField(max_length=200, null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField(null=False)
    tokens = models.TextField(null=True)
    stems = models.JSONField(verbose_name="post stems", null=True)
    pos_tags = models.JSONField(verbose_name="post part of speech tags", null=True)
    lemma = models.JSONField(verbose_name="post lemma", null=True)

    def __str__(self):
        return f"Comment for post {self.post}"

    def save(self, *args, **kwargs):
        tokens = tokenize_words(self.content)
        stems = stem_sentence(tokens)
        pos_tags = pos_tags_sentence(tokens)
        lemma = lemmatize_sentence(tokens)
        self.tokens = "\t".join(tokens)
        self.stems = stems
        self.pos_tags = pos_tags
        self.lemma = lemma
        super(Comment, self).save()

backend/posts/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from django.http import JsonResponse
from django.core.paginator import Paginator
from .models import Post, Comment
from .serializers import PostSerializer, CommentSerializer
from reddit.helpers import get_posts



class Index(View):
    def get(self, request):
        return render(request, "index.html")


def postsView(request):
    if request.method == "GET":
        posts = Post.objects.all()
        paginator = Paginator(posts, 12)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        context = {
            "page_obj": page_obj
        }
        return render(request, "posts.html", context=context)


class WriteYourOwn(View):
    """
        Write your own stuff and then it will be processed 
        with nltk tools
    """
    def get(self, request):
        return render(request, "write_your_own.html", context={})



class ProcessData(View):
    """
        Process the data sent from the client by ajax
        and return all the parsed data
    """
    def post(self, request):
        if request.is_ajax():
            print(request.POST)
    


class Chatbot(View):
    """
        Choose an nltk bot to chat with
    """
    def get(self, request):
        context = {
            "chatbots": [
                "eliza",
                "iesha",
                "rude",
                "suntsu",
                "zen"
            ]
        }
        return render(request, "chatbot.html", context=context)

'''



const alpha = {
  "a": 1,
  "b": 2,
  "c": 3,
  "d": 4,
  "e": 5,
  "f": 6,
  "g": 7,
  "h": 8,
  "i": 9,
  "j": 10,
  "k": 11,
  "l": 12,
  "m": 13,
  "n": 14,
  "o": 15,
  "p": 16,
  "q": 17,
  "r": 18,
  "s": 19,
  "t": 20,
  "u": 22,
  "v": 23,
  "w": 24,
  "x": 25,
  "y": 26,
  "z": 27,
}


function alphabetPosition(text) {
  return text.split('').map(char => isNaN(char)? alpha[char.toLowerCase()]).join(' ')
}
'''

backend/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block styles %}
    {% endblock %}
    {% block title %}
    {% endblock %}
</head>
<body class="root">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand nav-logo" href="#"> NLP with Django </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainNav" aria-controls="mainNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="mainNav"> 
            <ul class="navbar-nav ml-auto"> 
                <li class="nav-item active">
                    <a href="{% url 'posts:index' %}"> Home </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'posts:posts' %}"> Posts </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'posts:tell-me' %}"> Tell me </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'posts:chatbot' %}"> Chatbot </a>
                </li>
            </ul>
        </div>
    </nav>

    {% block body %}
    {% endblock %}


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> 
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    {% block scripts %}
    {% endblock %}
</body>
</html>

backend/templates/chatbot.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/chatbot.css' %}">
{% endblock %}


{% block title %}
    <title> NLTK chatbot </title>
{% endblock %}


{% block body %}
    <div class="container">
        <div class="root" style="margin-top: 30px;">
            <div class="row" style="margin-bottom: 15px;">
                <div class="col-lg-8 col-md-8 col-xs-12">
                    <h5 class="title"> You can choose a bot to chat with! </h5>
                </div>
                <div class="col-lg-4 col-md-4 col-xs-12">
                    <div class="dropdown">
                        <button class="btn btn-secondary btn-sm dropdown-toggle" 
                            id="dropdownCBot" role="button" data-toggle="dropdown" 
                            aria-haspopup="true" aria-expanded="false" style="width: 100%;">
                            Bots
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownCBot">
                            {% for bot in chatbots %}
                                <a class="dropdown-item" name={{bot}} id="dd-bot-choice" href="#"> {{ bot }}  </a> 
                            {% endfor %}
                        </div>
                    </div>
                </div> 
            </div>
            <div>
                <div class="row">
                    <div class="col">
                        <div id="chat-area">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <form id="human-form" method="POST" autocomplete="off">
                            {% csrf_token %}
                            <div class="row" style="margin-top: 15px;">
                                <div class="col-lg-10 col-md-10 col-xs-12">
                                    <input name="human_message" id="human-message" type="text" placeholder="Talk with me ..."/>
                                </div>
                                <div class="col-lg-2 col-md-2 col-xs-12">
                                    <button type="submit" class="btn btn-success btn-sm" style="width: 100%"> Send </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}


{% block scripts %}
    <script src="{% static 'js/chatbot.js' %}"></script>
{% endblock %}

backend/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}" >
{% endblock %}


{% block title %}
    <title> Data Processing </title>
{% endblock %}


{% block body %}
    <div class="container">
        <h3 class="title"> Data processing with praw and django </h3>
        <section> 
            This web app uses praw library to fetch posts from reddit api and then add the posts
            to the django's ORM database. NLKT library is used to perform NLP tasks in the post itself 
            and the comments.
        </section>
        <section>
            NLTK (Natural Language ToolKit) is used to parse a corpus which is raw text into
            useful information that can be used later on for complex tasks such as:
            <ul>
                <li> Sentiment Analysis </li>
                <li> Entity named recognition </li>
                <li> Machine Translation </li>
                <li> Autocompletion </li>
                <li> Chatbots </li>
                <li> and even more... </li>
            </ul>
            The basic parsing techniques wich will be performed in the posts are:
            <ul>
                <li> Word Tokenization: split a sentece into words </li>
                <li> Bigrams: a set of two word tokens (ex. ("python", "rules")) </li>
                <li> Stemming: normalize a word into its root form (being the root not necessarily a word) </li> 
                <li> Lemmatization: normalize the worls in its root form (beign the root an actual word)  </li>
                <li> Stop words: words that are commonly used to connect two words but doesn't give information </li>
                <ul>
                    <li> Pronouns </li>
                    <li> Articles </li>
                    <li> Prepositions </li>
                    <li> ...etc </li>
                </ul>
            </ul>
        </section>
        <button class="btn btn-primary">
            Start
        </button>
    </div>
{% endblock %}


{% block scripts %}
{% endblock %}

backend/templates/post.html
{% extends 'base.html' %}
{% load static %}


{% block styles %}

{% endblock %}

{% block body %}
{% endblock %}


{% block body %}

{% endblock %}


{% block scripts %}

{% endblock %}

backend/templates/posts.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/posts.css' %}">
{% endblock %}


{% block title %}
    <title> Posts Processing </title>
{% endblock %}


{% block body %}
    <div class="container" style="margin-top: 20px;">

        <h4 style="text-align: center;"> Reddit posts about Python </h4>

        <div class="modal" tabindex="-1" id="post-modal"> 
            <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">  </h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div>
                        <p class="modal-author">  </p>
                    </div>
                    <div class="modal-body">
                    </div>
                    <div class="modal-footer">
                        <button type="button" id="modal-close-button" class="btn btn-danger" data-dismiss="modal"> Close </button>
                    </div>
                </div>
            </div>
        </div>

        
        <div class="post-container">
            <div class="row">
                {% for post in page_obj %}
                    <div class="col-lg-4 col-md-6 col-xs-12">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title"> {{ post.title }} </h5>
                                <h6 class="card-subtitle"> Author: {{ post.username }}  </h6>
                                <p class="card-text"> {{ post.content }} </p>
                                <span class="badge badge-success"> ups: {{ post.ups }} </span>
                                <span class="badge badge-danger"> downs: {{ post.downs }} </span>
                                <br/>
                                <div class="card-actions">
                                    <button class="btn btn-primary btn-sm detail-button" data-toggle="modal" data-target="#post-modal" id={{post.id}}> Comments </button>
                                    <a class="btn btn-secondary btn-sm" href="{{post.url}}" target="_blank"> url </a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div class="paginator">
            <span class="step-links">  
                {% if page_obj.has_previous %}
                    <a class="btn btn-secondary btn-sm" href="?page=1"> &laquo; first </a>
                    <a class="btn btn-secondary btn-sm" href="?page={{ page_obj.previous_page_number }}"> Prev </a>
                {% endif %}

                <span class="current">
                    {{ page_obj.number }} / {{ page_obj.paginator.num_pages }} 
                </span>

                {% if page_obj.has_next %}
                    <a class="btn btn-secondary btn-sm" href="?page={{ page_obj.next_page_number }}"> Next </a>
                    <a class="btn btn-secondary btn-sm" href="?page={{ page_obj.paginator.num_pages }}"> Last &raquo; </a>
                {% endif %}
            </span>
        </div>

    </div>
{% endblock %}


{% block scripts %}
    <!-- <script src="{% static 'js/posts.js' %}"></script> -->
    <script>
        $(".detail-button").click((event) => {
            event.preventDefault();
            const id = event.target.id;
            $.ajax({
                type: "GET",
                url: `http://127.0.0.1:8000/api/comments/${id}`,
                success: response => {
                    $(".modal-body").empty();
                    if (response.length >= 1) {
                        response.map(comment => {
                            $(".modal-body").append(`
                                <div>
                                    <p> ${comment.content} </p>
                                    <hr/>
                                </div>
                            `);
                        });
                    } 
                    else {
                        $(".modal-body").html("The post has no comments!");
                    }
                },
                error: error => {
                    console.log(error);
                }
            })
        });
    </script>
{% endblock %}

backend/templates/write_your_own.html
{% extends 'base.html' %}
{% load static %}


{% block styles %}
    <link rel="stylesheet" href="{% static 'css/write_your_own.css' %}">
{% endblock %}

{% block title %}
    <title> Write your own </title>
{% endblock %}


{% block body %}
    <div class="container">
        <div>
            <p> Write something here or copy text from another source to parse its content  </p>
            <form id="wyoform" method="POST">
                {% csrf_token %}
                <textarea name="tms" id="tms" rows="10"></textarea> 
                <br/>
                <button type="submit" class="btn btn-primary btn-lg" id="submit-btn"> Process </button>
            </form>
        </div>

        <div class="wyo-processing">
            <h5 class="wyo-title"> The sentence was processed </h5>
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead class="thead-dark">
                        <tr>
                            <th> Level </th>
                            <th> Data </th>
                        </tr>
                    </thead>
                    <tbody id="wyo-body">
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}


{% block scripts %}
    <script>
        console.log("Write your own...");

        $(document).ready(() => {
            $(".wyo-processing").hide();
        });

        $("#submit-btn").click(event => {
            event.preventDefault();
            const text = $("#tms").val();
            const encoded_form = $("#wyoform").serialize();
            if ( text !== "" ) {
                $.ajax({
                    type: "post",
                    url: "http://127.0.0.1:8000/api/posts/parse",
                    data: encoded_form,
                    success: response => {
                        console.log(response)
                        const sentence_no_stop_words = response["sentence_no_stop_words"].join(" ");
                        const sentence_tokens = response["sentence_tokens"].map(token => (
                            `< ${token} >`
                        ));
                        const sentence_stems = response["sentence_stems"].map(item => (
                            `< ${item} >`
                        ));
                        const sentence_pos_tags = response["sentence_pos"].map(item => (
                            `< ${item} >`
                        ));
                        const sentence_lemma = response["sentence_lemma"].map(item => Object.entries(item)).map(item => `<${item[0]}: ${item[1]}>`)
                        $(".wyo-processing").show();
                        $("#wyo-body").html("");
                        $("#wyo-body").append(`
                            <tr>
                                <td> No stop words  </td>
                                <td> ${ sentence_no_stop_words }  </td>
                            </tr>
                            <tr>
                                <td> Word tokens  </td>
                                <td> ${ sentence_tokens } </td>
                            </tr>
                            <tr>
                                <td> Word stems  </td>
                                <td> ${ sentence_stems } </td>
                            </tr>
                            <tr>
                                <td> POS tags </td>
                                <td> ${ sentence_pos_tags } </td>
                            </tr>
                            <tr>
                                <td> Words Lemma </td>
                                <td> ${ sentence_lemma } </td>
                            </tr>
                        `);
                    },
                    error: err => {
                        console.log(err)
                    }
                });
            }
        });
    </script>
{% endblock %}